# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
sphinx:
  configuration: docs/conf.py
# formats: all  ## none appart from html required here
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
