name: packaging

on:
  # Make sure packaging process is not broken
  push:
    branches: [main, dev]
  pull_request:
  # Make a package for release
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v7
    - name: Set up uv and Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v10.2.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create packages
      run: uv build
    - name: Run twine check
      run: uvx twine check dist/*
    - uses: actions/upload-artifact@v7
      with:
        name: tox-gh-actions-dist
        path: dist
